import Head from "next/head";
import Header from "../components/common/header";
import TopLeftMenu from "../components/common/topLeftMenu";
import TopProfile from "../components/cards/topProfile";

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <div className="bg-top-bg h-screen">
        <div className="flex max-w-5xl mx-auto">
          <TopLeftMenu />
          <div className="flex flex-wrap pt-10 ml-3">
            <TopProfile />
            <TopProfile />
            <TopProfile />
            <TopProfile />
          </div>
        </div>
      </div>
    </div>
  );
}
